/**
 * ✅ SECURE CSRF Protection
 * CRITICAL: Token must be generated by BACKEND, not frontend!
 * Frontend only reads and sends the token
 */

class CSRFProtection {
  private static instance: CSRFProtection;
  private readonly COOKIE_NAME = 'csrf-token';
  private readonly META_NAME = 'csrf-token';

  private constructor() {}

  static getInstance(): CSRFProtection {
    if (!CSRFProtection.instance) {
      CSRFProtection.instance = new CSRFProtection();
    }
    return CSRFProtection.instance;
  }

  /**
   * ✅ CORRECT: Get CSRF token from backend-set cookie
   * Backend must set: Set-Cookie: csrf-token=xxx; Path=/; SameSite=Strict
   */
  async getToken(): Promise<string> {
    // Method 1: Try cookie (preferred)
    const cookieToken = this.getTokenFromCookie();
    if (cookieToken) {
      return cookieToken;
    }

    // Method 2: Try meta tag (for SSR pages)
    const metaToken = this.getTokenFromMeta();
    if (metaToken) {
      return metaToken;
    }

    // Method 3: Fetch from backend endpoint
    try {
      const token = await this.fetchTokenFromBackend();
      return token;
    } catch (error) {
      console.error('Failed to fetch CSRF token:', error);
      throw new Error('CSRF token not available. Please refresh the page.');
    }
  }

  /**
   * Read CSRF token from cookie (set by backend)
   */
  private getTokenFromCookie(): string | null {
    if (typeof document === 'undefined') return null;

    const cookies = document.cookie.split(';');
    for (const cookie of cookies) {
      const [name, value] = cookie.trim().split('=');
      if (name === this.COOKIE_NAME) {
        return decodeURIComponent(value);
      }
    }

    return null;
  }

  /**
   * Read CSRF token from meta tag (for SSR pages)
   * Backend should render: <meta name="csrf-token" content="xxx">
   */
  private getTokenFromMeta(): string | null {
    if (typeof document === 'undefined') return null;

    const meta = document.querySelector(`meta[name="${this.META_NAME}"]`);
    return meta ? meta.getAttribute('content') : null;
  }

  /**
   * ✅ Fetch fresh CSRF token from backend
   * Backend should have endpoint: GET /api/auth/csrf
   * Response: { csrfToken: "xxx" }
   * And set cookie: Set-Cookie: csrf-token=xxx
   */
  private async fetchTokenFromBackend(): Promise<string> {
    const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/auth/csrf`, {
      method: 'GET',
      credentials: 'include', // Send cookies
    });

    if (!response.ok) {
      throw new Error('Failed to fetch CSRF token from backend');
    }

    const data = await response.json();
    return data.csrfToken;
  }

  /**
   * Get CSRF headers for API requests
   */
  async getHeaders(): Promise<Record<string, string>> {
    const token = await this.getToken();
    return {
      'X-CSRF-Token': token,
      'X-Requested-With': 'XMLHttpRequest',
    };
  }

  /**
   * ❌ REMOVED: Client-side token generation
   * ❌ REMOVED: Token validation (backend handles this)
   * ❌ REMOVED: Token rotation (backend handles this)
   */

  /**
   * Force refresh CSRF token from backend
   * Call this after sensitive operations
   */
  async refreshToken(): Promise<string> {
    return await this.fetchTokenFromBackend();
  }
}

// Export singleton
export const csrfProtection = CSRFProtection.getInstance();

/**
 * Hook-friendly CSRF token getter
 */
export async function getCSRFToken(): Promise<string> {
  return await csrfProtection.getToken();
}

/**
 * Get CSRF headers for fetch/axios
 */
export async function getCSRFHeaders(): Promise<Record<string, string>> {
  return await csrfProtection.getHeaders();
}

/**
 * Refresh CSRF token from backend
 */
export async function refreshCSRFToken(): Promise<string> {
  return await csrfProtection.refreshToken();
}

/**
 * ⚠️ BACKEND REQUIREMENTS:
 *
 * 1. Generate CSRF token on session creation:
 *    - Use crypto.randomBytes(32) or equivalent
 *    - Store in session: req.session.csrfToken = token
 *
 * 2. Set CSRF cookie on all responses:
 *    res.cookie('csrf-token', token, {
 *      httpOnly: false, // Frontend needs to read this
 *      secure: true,    // HTTPS only
 *      sameSite: 'strict',
 *      maxAge: 3600000  // 1 hour
 *    });
 *
 * 3. Validate CSRF on all non-GET requests:
 *    const clientToken = req.headers['x-csrf-token'];
 *    const sessionToken = req.session.csrfToken;
 *    if (clientToken !== sessionToken) {
 *      return res.status(403).json({ error: 'Invalid CSRF token' });
 *    }
 *
 * 4. Provide CSRF endpoint:
 *    GET /api/auth/csrf
 *    - Return { csrfToken: req.session.csrfToken }
 *    - Set cookie in response
 */